# Generated by Django 4.2.3 on 2023-11-28 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='note',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='orders',
            name='order_data',
            field=models.TextField(default=''),
        ),
    ]
